# Generated by Django 2.2 on 2020-09-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('roll', models.FloatField()),
                ('acc_x', models.FloatField()),
                ('acc_y', models.FloatField()),
                ('acc_z', models.FloatField()),
            ],
            options={
                'db_table': 'tbl_door',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('rate', models.FloatField()),
                ('consumption', models.FloatField()),
            ],
            options={
                'db_table': 'tbl_power',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('code', models.CharField(max_length=128)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'tbl_temperature',
            },
        ),
    ]
